// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jutzxpcqdgndqdiavnbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1dHp4cGNxZGduZHFkaWF2bmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDcyMTYsImV4cCI6MjA2NTkyMzIxNn0.M3qstWqrTb32TphWNU4aX5y26yQs7T2WrWZSd_L81LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);